[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Variables de entorno para Auth0 (configurar en Netlify Dashboard)
[context.production.environment]
  AUTH0_SECRET = "your-auth0-secret"
  AUTH0_BASE_URL = "https://your-site.netlify.app"
  AUTH0_DOMAIN = "your-tenant.auth0.com"
  AUTH0_CLIENT_ID = "your-auth0-client-id"
  AUTH0_CLIENT_SECRET = "your-auth0-client-secret"

# Redirecciones para APIs (incluyendo Auth0)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirección específica para debug del callback de Auth0
[[redirects]]
  from = "/api/auth/callback"
  to = "/debug-callback.html"
  status = 200

# Redirección principal a login
[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

# Redirección SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para funciones
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
